### ISSUE TITLE
Low/Medium priority: Notify user during program conversions

### ISSUE THREAD

**Issue by TateThomas** [ngsorenson/UVSim#30]
Converting from 4bit to 6bit will add a zero in between opcode and address, if the opcode is detected. Sometimes, that may not be intended, since it could be a number, so it would be best to notify (maybe in the output frame) where opcodes were detected.

Converting from 6bit to 4bit can lose data (since numbers can be larger in 6bit), so it would be good to maybe have a pop up notifying the user, and asking them if it is ok to continue.

**Comment by ngsorenson** [comment]
I added a warning in the version change popup to put the responsibility on the user if they change versions with files loaded into memory. 

Since we all seemed to agree that version switching should be good enough for the scope of the project and that we weren't going to officially support automatic conversion from "4 bit" to "6 bit," I'm fine with leaving it as is.

**Comment by jthomaschappell** [comment]
How will this fail gracefully if the user makes the wrong call?

**Comment by ngsorenson** [comment]
> How will this fail gracefully if the user makes the wrong call?

Current conversion implementation doesn't fail. It could "corrupt" some lines of their program when the first 2 digits of a line get read as an opcode when they're actually meant to be part of a number (hypothetical: decimal value 1015 vs. opcode 10 on memory address 15). As per Prof. Burtt's Canvas message on 4/3 - none of the test files will have lines with opcodes in the first 2 digits unless they are meant to be instructions. Unless I'm misunderstanding his message, we are not required to worry about this edge case unless we want to.

**Comment by ngsorenson** [comment]
In regards to 6-digit to 4-digit conversion, there is no avoiding the loss of 2 digits, which will result in a lot of lines being corrupted unless the 2 digits lost were leading zeros.

> I added a warning in the version change popup to put the responsibility on the user if they change versions with files loaded into memory.

The wording I used in the warning leads one to believe that it's a guaranteed corruption of the program in memory, which isn't entirely true. We can change it to be less aggressive and/or provide more information about the limitations of the automatic conversion, but I originally chose to keep it short so that a wall of text doesn't make the popup look too much worse than it already does.
